spring:
  application:
    name: catsapi
  datasource:
    url: jdbc:h2:mem:cats
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  management:
    endpoints:
      web:
        exposure:
          include: "*"