{
 "title": "TheCatsApi-app",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_range", "label": "Time range for aggregations", "query": "1m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Heap space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "JVM Heap Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "run - time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "it_minetti_demo_service_RandomSumService_run_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "run - counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(it_minetti_demo_service_RandomSumService_run_seconds_count{exception=\"none\",}[$time_range])",
     "legendFormat": "ok"
    }
   ]
  },
  {
   "title": "runLong - time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "it_minetti_demo_service_RandomSumService_runLong_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "REST hi - count",
   "type": "graph",
   "description": "Endpoint: catsapi:8080/hi",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(it_minetti_demo_OnDemandController_hi_seconds_count{exception=\"none\"}[$time_range])",
     "legendFormat": "ok"
    },
    {
     "expr": "increase(it_minetti_demo_OnDemandController_hi_seconds_count{exception!=\"none\"}[$time_range])",
     "legendFormat": "{{exception}}"
    },
    {
     "expr": "sum(increase(it_minetti_demo_OnDemandController_hi_seconds_count[$time_range]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}